Repository kaiiyer/rajappan, pull requests merged in 2021-10, with the labels that each got.

#39 Updated Readme
  README.md
  privacy/README.md
Labels: hacktoberfest-accepted

#40 Update README.md
  privacy/README.md
Labels: documentation, hacktoberfest

#41 Update README.md
  docs/README.md
Labels: hacktoberfest, hacktoberfest-accepted
